Repository wpmudev/sui-react, pull requests merged in 2023-10, with the labels that each got.

#135 Footer Component
  packages/components/footer/src/footer.tsx
  packages/components/footer/stories/Footer.mdx
  packages/components/footer/stories/images/anatomy-free.svg
  packages/components/footer/stories/images/anatomy-pro.svg
  packages/components/footer/stories/images/focus-state.svg
  packages/components/footer/stories/images/free-desktop-spacing.svg
  packages/components/footer/stories/images/free-mobile-spacing.svg
  packages/components/footer/stories/images/free-tablet-spacing.svg
  packages/components/footer/stories/images/free.svg
  packages/components/footer/stories/images/hover-state.svg
  packages/components/footer/stories/images/pro-mobile-spacing.svg
  packages/components/footer/stories/images/pro.svg
  packages/components/footer/stories/tabs/TabCode.mdx
  packages/components/footer/stories/tabs/TabExamples.mdx
  packages/components/footer/stories/tabs/TabUsage.mdx
Labels: documentation

#134 Navigation component
  packages/components/navigation/src/navigation.types.ts
  packages/components/navigation/stories/images/accounts-states.svg
  packages/components/navigation/stories/images/anatomy.svg
  packages/components/navigation/stories/images/behaviour.svg
  packages/components/navigation/stories/images/max-width.svg
  packages/components/navigation/stories/images/spacing.svg
  packages/components/navigation/stories/navigation.mdx
  packages/components/navigation/stories/navigation.stories.tsx
  packages/components/navigation/stories/tabs/TabCode.mdx
  packages/components/navigation/stories/tabs/TabExamples.mdx
  packages/components/navigation/stories/tabs/TabUsage.mdx
Labels: documentation

#133 ✨ new(uploader): uploader accessible fixes.
  packages/components/uploader/src/uploader.tsx
  packages/components/uploader/stories/Uploader.stories.tsx
  packages/components/uploader/stories/tabs/TabCode.mdx
  packages/components/uploader/stories/tabs/TabExamples.mdx
Labels: enhance

#132 Dashboard widget
  packages/components/dashboard-widget/stories/dashboard-widget.mdx
  packages/components/dashboard-widget/stories/dashboard-widget.stories.tsx
  packages/components/dashboard-widget/stories/images/anatomy.svg
  packages/components/dashboard-widget/stories/images/body-examples.svg
  packages/components/dashboard-widget/stories/images/clickable.svg
  packages/components/dashboard-widget/stories/images/footer-examples.svg
  packages/components/dashboard-widget/stories/images/header-examples.svg
  packages/components/dashboard-widget/stories/images/header.svg
  packages/components/dashboard-widget/stories/images/pro.svg
  packages/components/dashboard-widget/stories/images/spacing.svg
  packages/components/dashboard-widget/stories/images/status.svg
  packages/components/dashboard-widget/stories/tabs/Examples/Example.tsx
  packages/components/dashboard-widget/stories/tabs/TabCode.mdx
  packages/components/dashboard-widget/stories/tabs/TabExamples.mdx
  packages/components/dashboard-widget/stories/tabs/TabUsage.mdx
Labels: documentation

#131 Table component
  packages/components/table/src/table-head.tsx
  packages/components/table/src/table.types.ts
  packages/components/table/stories/ReactTable.mdx
  packages/components/table/stories/images/anatomy.svg
  packages/components/table/stories/images/button-filter.svg
  packages/components/table/stories/images/draggable.svg
  packages/components/table/stories/images/inline-filter.svg
  packages/components/table/stories/images/large-number-columns.svg
  packages/components/table/stories/images/popover-filter.svg
  packages/components/table/stories/images/responsive.svg
  packages/components/table/stories/images/sort-column.svg
  packages/components/table/stories/images/spacing-cell.svg
  packages/components/table/stories/images/spacing-footer.svg
  packages/components/table/stories/images/spacing-row.svg
  packages/components/table/stories/images/state-default.svg
  packages/components/table/stories/images/state-expanded.svg
  packages/components/table/stories/images/state-hover.svg
  packages/components/table/stories/images/status.svg
  packages/components/table/stories/images/type-default.svg
  packages/components/table/stories/images/type-stripe.svg
  packages/components/table/stories/tabs/Examples/Drag.mdx
  packages/components/table/stories/tabs/Examples/Example.tsx
  packages/components/table/stories/tabs/Examples/Selection.mdx
  packages/components/table/stories/tabs/Examples/Stripe.mdx
  packages/components/table/stories/tabs/Examples/Toolbar.mdx
  packages/components/table/stories/tabs/TabCode.mdx
  packages/components/table/stories/tabs/TabExamples.mdx
  packages/components/table/stories/tabs/TabUsage.mdx
Labels: documentation

#130 ✨ new(summary): summary tooltip markup fix.
  packages/components/color-picker/stories/ReactColorPicker.stories.tsx
  packages/components/config-table/src/config-table.tsx
  packages/components/summary-box/src/summary-box-item.tsx
Labels: enhance

#129 Upsell Notice
  packages/components/upsell-notice/src/upsell-notice.types.ts
  packages/components/upsell-notice/stories/images/anatomy.svg
  packages/components/upsell-notice/stories/images/high-contrast-mode.svg
  packages/components/upsell-notice/stories/images/location.svg
  packages/components/upsell-notice/stories/images/spacings.svg
  packages/components/upsell-notice/stories/tabs/Examples/Beehive.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Branda.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Defender.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Forminator.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Hummingbird.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Hustle.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Ivt.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Shipper.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Smartcrawl.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Smush.mdx
  packages/components/upsell-notice/stories/tabs/Examples/Snapshot.mdx
  packages/components/upsell-notice/stories/tabs/TabCode.mdx
  packages/components/upsell-notice/stories/tabs/TabExamples.mdx
  packages/components/upsell-notice/stories/tabs/TabUsage.mdx
  packages/components/upsell-notice/stories/upsell-notice.mdx
Labels: documentation

#128 New(Upsell): documentation, Usage Page
  packages/components/upsell/src/upsell.tsx
  packages/components/upsell/src/upsell.types.ts
  packages/components/upsell/stories/images/anatomy.svg
  packages/components/upsell/stories/images/location.svg
  packages/components/upsell/stories/images/padding-desktop.svg
  packages/components/upsell/stories/images/spacing-desktop.svg
  packages/components/upsell/stories/images/spacing-mobile.svg
  packages/components/upsell/stories/images/spacing-tablet.svg
  packages/components/upsell/stories/tabs/Examples/Beehive.mdx
  packages/components/upsell/stories/tabs/Examples/Branda.mdx
  packages/components/upsell/stories/tabs/Examples/Defender.mdx
  packages/components/upsell/stories/tabs/Examples/Forminator.mdx
  packages/components/upsell/stories/tabs/Examples/Hummingbird.mdx
  packages/components/upsell/stories/tabs/Examples/Hustle.mdx
  packages/components/upsell/stories/tabs/Examples/Ivt.mdx
  packages/components/upsell/stories/tabs/Examples/Shipper.mdx
  packages/components/upsell/stories/tabs/Examples/Smartcrawl.mdx
  packages/components/upsell/stories/tabs/Examples/Smush.mdx
  packages/components/upsell/stories/tabs/Examples/Snapshot.mdx
  packages/components/upsell/stories/tabs/TabCode.mdx
  packages/components/upsell/stories/tabs/TabExamples.mdx
  packages/components/upsell/stories/tabs/TabUsage.mdx
  packages/components/upsell/stories/upsell.mdx
Labels: documentation

#126 Integration
  packages/components/integration/src/integration.tsx
  packages/components/integration/src/integration.types.ts
  packages/components/integration/stories/ReactIntegration.mdx
  packages/components/integration/stories/ReactIntegration.stories.js
  packages/components/integration/stories/images/anatomy.svg
  packages/components/integration/stories/images/high-contrast.svg
  packages/components/integration/stories/images/location.svg
  packages/components/integration/stories/images/spacing.svg
  packages/components/integration/stories/images/types.svg
  packages/components/integration/stories/tabs/Examples/Active.mdx
  packages/components/integration/stories/tabs/Examples/Disabled.mdx
  packages/components/integration/stories/tabs/Examples/Pro.mdx
  packages/components/integration/stories/tabs/TabCode.mdx
  packages/components/integration/stories/tabs/TabExamples.mdx
  packages/components/integration/stories/tabs/TabUsage.mdx
Labels: documentation

#109 Field list component
  packages/components/field-list/src/field-list.tsx
  packages/components/field-list/src/field-list.types.ts
  packages/components/field-list/src/index.ts
  packages/components/field-list/stories/ReactFieldList.mdx
  packages/components/field-list/stories/ReactFieldList.stories.js
  packages/components/field-list/stories/images/anatomy.svg
  packages/components/field-list/stories/images/spacings.svg
  packages/components/field-list/stories/tabs/TabCode.mdx
  packages/components/field-list/stories/tabs/TabExamples.mdx
  packages/components/field-list/stories/tabs/TabUsage.mdx
Labels: documentation

#122 Search documentation
  packages/components/search/src/search.types.ts
  packages/components/search/stories/images/anatomy.svg
  packages/components/search/stories/images/example.svg
  packages/components/search/stories/images/smart-search-example.svg
  packages/components/search/stories/images/smart-search.svg
  packages/components/search/stories/images/spacings.svg
  packages/components/search/stories/images/states.svg
  packages/components/search/stories/images/types.svg
  packages/components/search/stories/options.js
  packages/components/search/stories/search.mdx
  packages/components/search/stories/search.stories.js
  packages/components/search/stories/tabs/TabCode.mdx
  packages/components/search/stories/tabs/TabExamples.mdx
  packages/components/search/stories/tabs/TabUsage.mdx
Labels: documentation

#124 Basic box
  packages/components/basic-box/src/basic-box.tsx
  packages/components/basic-box/src/basic-box.types.ts
  packages/components/basic-box/stories/basic-box.mdx
  packages/components/basic-box/stories/images/anatomy.svg
  packages/components/basic-box/stories/images/configs.svg
  packages/components/basic-box/stories/images/examples.svg
  packages/components/basic-box/stories/images/sideimage.svg
  packages/components/basic-box/stories/images/spacings.svg
  packages/components/basic-box/stories/tabs/Examples/Informative.mdx
  packages/components/basic-box/stories/tabs/Examples/Neutral.mdx
  packages/components/basic-box/stories/tabs/Examples/Success.mdx
  packages/components/basic-box/stories/tabs/TabCode.mdx
  packages/components/basic-box/stories/tabs/TabExamples.mdx
  packages/components/basic-box/stories/tabs/TabUsage.mdx
Labels: documentation

#125 Setting block
  packages/components/setting-block/stories/images/anatomy.svg
  packages/components/setting-block/stories/images/examples.svg
  packages/components/setting-block/stories/images/spacings.svg
  packages/components/setting-block/stories/images/types.svg
  packages/components/setting-block/stories/setting-block.mdx
  packages/components/setting-block/stories/setting-block.stories.js
  packages/components/setting-block/stories/tabs/TabCode.mdx
  packages/components/setting-block/stories/tabs/TabExamples.mdx
  packages/components/setting-block/stories/tabs/TabUsage.mdx
Labels: documentation

#113 Rich Text Editor Component
  packages/components/rich-text-editor/src/rich-text-editor.tsx
  packages/components/rich-text-editor/src/rich-text-editor.types.ts
  packages/components/rich-text-editor/stories/RichTextEditor.mdx
  packages/components/rich-text-editor/stories/RichTextEditor.stories.tsx
  packages/components/rich-text-editor/stories/images/anatomy.png
  packages/components/rich-text-editor/stories/images/anatomy.svg
  packages/components/rich-text-editor/stories/images/spacing.svg
  packages/components/rich-text-editor/stories/images/types.svg
  packages/components/rich-text-editor/stories/tabs/TabCode.mdx
  packages/components/rich-text-editor/stories/tabs/TabExamples.mdx
  packages/components/rich-text-editor/stories/tabs/TabUsage.mdx
Labels: documentation

#145 Eslint Fixes, Phase 00
  mdx.d.ts
  package-lock.json
  package.json
  packages/components/accordion/__tests__/accordion.test.tsx
  packages/components/alert-banner/src/alert-banner.tsx
  packages/components/alert-banner/stories/alert-banner.stories.tsx
  packages/components/box/stories/ReactBox.stories.js
  packages/components/box/tsconfig.json
  packages/components/builder/src/builder-field.tsx
  packages/components/builder/stories/builder.stories.tsx
  packages/components/button/stories/ReactButton.stories.tsx
  packages/components/button/tsconfig.json
  packages/components/checkbox/stories/tabs/Examples/BasicCheckbox.tsx
  packages/components/code-editor/stories/ReactCodeEditor.stories.tsx
  packages/components/code-snippet/stories/ReactCodeSnippet.stories.tsx
  packages/components/color-picker/src/elements/picker.tsx
  packages/components/color-picker/stories/ReactColorPicker.stories.tsx
  packages/components/dashboard-widget/src/dashboard-widget.tsx
  packages/components/dashboard-widget/stories/dashboard-widget.stories.tsx
  packages/components/dashboard-widget/stories/tabs/Examples/Example.tsx
  packages/components/date-picker/src/date-picker-context.tsx
  packages/components/date-picker/src/helpers.ts
  packages/components/date-picker/stories/DatePicker.stories.tsx
  packages/components/date-picker/stories/tabs/TabExamples.mdx
  packages/components/dropdown/src/dropdown-menu-item.tsx
  packages/components/dropdown/stories/dropdown.stories.tsx
  packages/components/editor-toolbar/stories/editor-toolbar.stories.tsx
  packages/components/empty-state/src/empty-state.tsx
  packages/components/empty-state/stories/empty-state.stories.tsx
  packages/components/field-list/stories/ReactFieldList.stories.tsx
  packages/components/field-password/src/field-password.tsx
  packages/components/field-password/stories/ReactFieldPassword.stories.tsx
  packages/components/footer/src/footer.tsx
  packages/components/footer/stories/footer.stories.tsx
  packages/components/segmented-control/src/segmented-control.types.ts
Labels: enhance

#136 Fix(Tooltip): Icon name not being provided
  packages/components/tooltip/src/tooltip.tsx
Labels: bug

#142 Select Documentation
  packages/components/select/stories/ReactSelect.mdx
  packages/components/select/stories/images/anatomy-expanded.png
  packages/components/select/stories/images/anatomy-multiselect.png
  packages/components/select/stories/images/anatomy-select.png
  packages/components/select/stories/images/expanded-anatomy.svg
  packages/components/select/stories/images/expanded-states.svg
  packages/components/select/stories/images/multiselect-anatomy.svg
  packages/components/select/stories/images/multiselect-states.svg
  packages/components/select/stories/images/single-anatomy.svg
  packages/components/select/stories/images/single-states.svg
  packages/components/select/stories/images/sizes.svg
  packages/components/select/stories/images/smart-anatomy.svg
  packages/components/select/stories/images/smart-expanded.svg
  packages/components/select/stories/images/smart-states.svg
  packages/components/select/stories/tabs/Examples/Size.mdx
  packages/components/select/stories/tabs/Examples/States.mdx
  packages/components/select/stories/tabs/Examples/Types.mdx
  packages/components/select/stories/tabs/Examples/Variants.mdx
  packages/components/select/stories/tabs/TabCode.mdx
  packages/components/select/stories/tabs/TabExamples.mdx
  packages/components/select/stories/tabs/TabUsage.mdx
Labels: documentation

#144 Radio Component
  packages/components/radio/src/radio.tsx
  packages/components/radio/stories/ReactRadio.mdx
  packages/components/radio/stories/ReactRadio.stories.js
  packages/components/radio/stories/images/alignment.svg
  packages/components/radio/stories/images/anatomy.svg
  packages/components/radio/stories/images/compound-states.svg
  packages/components/radio/stories/images/compound.svg
  packages/components/radio/stories/images/error-state.svg
  packages/components/radio/stories/images/interactive-state.svg
  packages/components/radio/stories/images/radio-group.svg
  packages/components/radio/stories/images/size.svg
  packages/components/radio/stories/images/state.svg
  packages/components/radio/stories/images/wrap-behavior.svg
  packages/components/radio/stories/tabs/Examples/States.mdx
  packages/components/radio/stories/tabs/Examples/Types.mdx
  packages/components/radio/stories/tabs/TabCode.mdx
  packages/components/radio/stories/tabs/TabExamples.mdx
  packages/components/radio/stories/tabs/TabUsage.mdx
Labels: documentation

#146 Eslint Fix Phase 01
  package.json
  packages/components/form-field/stories/ReactFormField.stories.tsx
  packages/components/grid/__tests__/grid.test.js
  packages/components/icon/__tests__/icon.test.js
  packages/components/link/src/link.types.ts
  packages/components/link/stories/link.stories.tsx
  packages/components/modal/stories/ReactModal.stories.js
  packages/components/navigation/src/navigation-brand.tsx
  packages/components/navigation/src/navigation.tsx
  packages/components/navigation/stories/navigation.stories.tsx
  packages/components/notification/src/notification.tsx
  packages/components/notification/stories/Notification.stories.js
  packages/components/notification/stories/Notification.stories.tsx
  packages/components/pagination/stories/ReactPagination.stories.tsx
  packages/components/pagination/stories/tabs/Examples/Examples.tsx
  packages/components/progress-bar/src/elements/indicator.tsx
  packages/components/progress-bar/src/elements/label.tsx
  packages/components/progress-bar/src/elements/value.tsx
  packages/components/progress-bar/src/progress-bar-value.tsx
  packages/components/progress-bar/src/progress-bar.tsx
  packages/components/progress-bar/stories/ReactProgressBar.stories.js
  packages/components/radio/stories/ReactRadio.stories.tsx
  packages/components/recipient/src/recipient.tsx
  packages/components/recipient/stories/ReactRecipient.stories.tsx
  packages/components/recipient/stories/images/person.png
  packages/components/recipient/stories/images/unreal-person.jpg
  packages/components/recipient/stories/tabs/Examples/Types.mdx
  packages/components/recipient/stories/tabs/TabExamples.mdx
  packages/components/rich-text-editor/__tests__/rich-test-editor.test.js
  packages/components/rich-text-editor/stories/RichTextEditor.stories.tsx
  packages/components/score/stories/ReactScore.stories.tsx
  packages/components/search/__tests__/search.test.tsx
  packages/components/search/stories/search.stories.js
  packages/components/segmented-control/src/segmented-control-button.tsx
  packages/components/segmented-control/stories/SegmentedControl.stories.tsx
  packages/components/select/__tests__/select.test.tsx
  packages/components/select/src/variants/select-multiselect.tsx
  packages/components/select/src/variants/select-search.tsx
  packages/components/select/src/variants/select-standard.tsx
  packages/components/select/stories/ReactSelect.stories.tsx
  packages/components/selector/src/selector.option.tsx
  packages/components/selector/src/selector.tsx
  packages/components/selector/src/selector.types.ts
  packages/components/setup-banner/src/setup-banner.tsx
  packages/components/setup-banner/stories/setup-banner.stories.tsx
Labels: enhance

#147 Eslint fixe phase 02
  packages/common/advanced/__tests__/sui-advanced.test.js
  packages/common/collections/__tests__/sui-collections.test.js
  packages/common/core/__tests__/sui-core.test.js
  packages/common/forms/__tests__/sui-forms.test.js
  packages/common/modules/__tests__/sui-modules.test.js
  packages/components/sidebar/src/sidebar-item.tsx
  packages/components/sidebar/stories/tabs/Examples/GeneralSidebar.tsx
  packages/components/spinner/__tests__/spinner.test.tsx
  packages/components/spinner/src/spinner-hook.tsx
  packages/components/spinner/stories/spinner.stories.tsx
  packages/components/spinner/stories/tabs/Examples/HookExample.tsx
  packages/components/summary-box/src/summary-box-footer.tsx
  packages/components/summary-box/src/summary-box-item.tsx
  packages/components/summary-box/src/summary-box.tsx
  packages/components/summary-box/stories/summary-box.stories.tsx
  packages/components/table/src/table-cell.tsx
  packages/components/table/src/table-head.tsx
  packages/components/table/src/table-toolbar.tsx
  packages/components/table/stories/tabs/Examples/Example.tsx
  packages/components/tabs/src/elements/tab-nav.tsx
  packages/components/tabs/src/elements/tab-panel.tsx
  packages/components/tag/stories/ReactTag.stories.tsx
  packages/components/textarea/stories/ReactTextarea.stories.tsx
  packages/components/toggle/src/toggle.types.ts
  packages/components/toggle/stories/ReactToggle.stories.tsx
  packages/components/tooltip/src/index.ts
  packages/components/tooltip/src/tooltip.types.ts
  packages/components/tooltip/stories/ReactTooltip.stories.tsx
  packages/components/uploader/__tests__/uploader.test.tsx
  packages/components/upsell/src/upsell.tsx
  packages/components/upsell/stories/upsell.stories.tsx
  packages/hooks/__tests__/react-utils.test.js
  packages/utils/__tests__/util.test.js
  packages/utils/src/index.ts
Labels: enhance

#140 ✨ new(design): design check of components.
  package.json
  packages/components/alert-banner/stories/alert-banner.stories.tsx
  packages/components/avatar/package.json
  packages/components/basic-box/package.json
  packages/components/box/package.json
  packages/components/builder/package.json
  packages/components/button/package.json
  packages/components/checkbox/package.json
  packages/components/checkbox/stories/ReactCheckbox.stories.js
  packages/components/config-table/package.json
  packages/components/dashboard-widget/package.json
  packages/components/date-picker/package.json
  packages/components/dropdown/package.json
  packages/components/editor-toolbar/package.json
  packages/components/editor-toolbar/src/editor-toolbar.tsx
  packages/components/empty-state/package.json
  packages/components/field-list/package.json
  packages/components/field-password/package.json
  packages/components/footer/package.json
  packages/components/form-field/package.json
  packages/components/grid/package.json
  packages/components/input/stories/ReactInput.stories.js
  packages/components/link/package.json
  packages/components/modal/package.json
  packages/components/navigation/package.json
  packages/components/notification/package.json
  packages/components/pagination/package.json
  packages/components/progress-bar/package.json
  packages/components/radio/package.json
  packages/components/search/package.json
  packages/components/segmented-control/package.json
  packages/components/selector/package.json
  packages/components/selector/src/selector.types.ts
  packages/components/selector/stories/selector.stories.tsx
  packages/components/setting-block/package.json
  packages/components/setup-banner/package.json
  packages/components/sidebar/package.json
  packages/components/spinner/package.json
  packages/components/summary-box/package.json
  packages/components/table/package.json
  packages/components/tabs/package.json
  packages/components/toggle/package.json
  packages/components/tooltip/stories/ReactTooltip.stories.tsx
  packages/components/uploader/package.json
  packages/components/upsell-notice/package.json
  packages/components/upsell/package.json
Labels: enhance

#127 ✨ new(checkbox): checkbox variations added.
  packages/ui/checkbox/src/checkbox-context.ts
  packages/ui/checkbox/src/checkbox-group.tsx
  packages/ui/checkbox/src/checkbox.tsx
  packages/ui/checkbox/src/checkbox.types.ts
  packages/ui/checkbox/src/index.ts
  packages/ui/checkbox/stories/ReactCheckbox.stories.js
Labels: enhance

#155 🐛 fix(eslint): Checkbox eslint issue fix.
  package-lock.json
  package.json
  packages/assets/css/src/scss/_utils/_tokens.scss
  packages/ui/accordion/__tests__/accordion.test.tsx
  packages/ui/checkbox/__tests__/checkbox.test.tsx
  packages/ui/checkbox/src/checkbox.tsx
  packages/ui/radio/stories/ReactRadio.stories.tsx
  packages/ui/tabs/package.json
  packages/ui/tabs/src/elements/tab-nav.tsx
Labels: bug
