Repository wpmudev/sui-react, pull requests merged in 2023-11, with the labels that each got.

#163 🐛 fix(global): components design improvements.
  .prettierignore
  packages/assets/css/src/scss/_components/_avatar/_elements/_build-status.scss
  packages/assets/css/src/scss/_components/_avatar/_modifiers/_build-size.scss
  packages/assets/css/src/scss/_core/_typography.scss
  packages/assets/css/src/scss/_utils/_tokens.scss
  packages/assets/css/src/tokens/avatar.json
  packages/assets/css/src/tokens/core.json
  packages/assets/icons/stories/IconsPack.stories.js
  packages/docs/src/components/list/list.scss
  packages/docs/src/components/page/page.scss
  packages/ui/button/src/button.tsx
  packages/ui/button/stories/ReactButton.mdx
  packages/ui/button/stories/images/correct-emphasis.svg
  packages/ui/button/stories/images/wrong-emphasis.svg
  packages/ui/button/stories/tabs/TabUsage.mdx
  packages/ui/grid/stories/images/grid.svg
  packages/ui/search/src/search.tsx
  packages/ui/search/src/search.types.ts
  packages/ui/search/stories/search.stories.js
Labels: enhance

#159 🐛 fix(upsell): upsell width fix.
  packages/assets/css/src/scss/_components/_upsell/_elements/_upsell-container.scss
  packages/assets/css/src/scss/_utils/_tokens.scss
  packages/assets/css/src/tokens/upsell.json
  packages/ui/upsell/stories/upsell.stories.tsx
Labels: bug

#160 🐛 fix(shadow): box shadow tokens added.
  packages/assets/css/src/scss/_components/_accordion/_accordion-elements/_build-panel.scss
  packages/assets/css/src/scss/_components/_avatar/_elements/_build-container.scss
  packages/assets/css/src/scss/_components/_builder/_elements/_builder-field.scss
  packages/assets/css/src/scss/_components/_builder/_modifiers/_builder-error.scss
  packages/assets/css/src/scss/_components/_color-picker/_elements/_build-color-picker.scss
  packages/assets/css/src/scss/_components/_color-picker/_elements/_build-input.scss
  packages/assets/css/src/scss/_components/_color-picker/_elements/_build-popover.scss
  packages/assets/css/src/scss/_components/_date-picker/_elements/_build-popover.scss
  packages/assets/css/src/scss/_components/_dropdown/_elements/_dropdown-popover.scss
  packages/assets/css/src/scss/_components/_integration/_elements/_build-container.scss
  packages/assets/css/src/scss/_components/_integration/_elements/_build-description.scss
  packages/assets/css/src/scss/_components/_integration/_states/_state-disabled.scss
  packages/assets/css/src/scss/_components/_integration/_states/_state-focus.scss
  packages/assets/css/src/scss/_components/_modal/_elements/_modal-container.scss
  packages/assets/css/src/scss/_components/_modal/_elements/_modal-header.scss
  packages/assets/css/src/scss/_components/_notification/_elements/_notification-container.scss
  packages/assets/css/src/scss/_components/_select/_states/_state-error.scss
  packages/assets/css/src/scss/_components/_select/_states/_state-open.scss
  packages/assets/css/src/scss/_components/_selector/_elements/_selector-container.scss
  packages/assets/css/src/scss/_components/_selector/_states/_state-hover.scss
  packages/assets/css/src/scss/_components/_sidebar/_elements/_sidebar-dropdown.scss
  packages/assets/css/src/scss/_components/_table/_table-elements/_build-table-row.scss
  packages/assets/css/src/scss/_components/_tabs/_tabs-elements/_build-container.scss
  packages/assets/css/src/scss/_components/_tree-view/_elements/_build-group.scss
  packages/assets/css/src/scss/_components/_tree-view/_elements/_build-info.scss
  packages/assets/css/src/scss/_components/_tree-view/_states/_state-active.scss
  packages/assets/css/src/scss/_components/_tree-view/_states/_state-disabled.scss
  packages/assets/css/src/scss/_components/_tree-view/_states/_state-focus.scss
  packages/assets/css/src/scss/_components/_tree-view/_states/_state-hover.scss
  packages/assets/css/src/scss/_utils/_tokens.scss
  packages/assets/css/src/tokens/colorpicker.json
  packages/assets/css/src/tokens/core.json
  packages/assets/css/src/tokens/integration.json
  packages/assets/css/src/tokens/tabs.json
  packages/assets/css/src/tokens/tree-view.json
  packages/ui/integration/stories/ReactIntegration.stories.js
Labels: bug

#164 Score Component
  packages/ui/score/stories/tabs/TabUsage.mdx
Labels: documentation

#151 Update Select Component
  .github/workflows/code-review.yml
  .gitignore
  packages/ui/config-table/__tests__/config-table.test.tsx
  packages/ui/pagination/src/pagination-nav.tsx
  packages/ui/select/stories/images/single-states.svg
  packages/ui/select/stories/tabs/TabUsage.mdx
Labels: documentation

#166 Des 90 functionality fixes
  .storybook/assets/css/wordpress/common.css
  packages/assets/css/src/scss/_components/_accordion/_accordion-elements/_build-header.scss
  packages/assets/css/src/scss/_components/_accordion/_states/_state-focus.scss
  packages/assets/css/src/scss/_components/_checkbox/_elements/_checkbox-box.scss
  packages/assets/css/src/scss/_components/_selector/_elements/_selector-delete.scss
  packages/assets/css/src/scss/_components/_selector/_elements/_selector-option.scss
  packages/assets/css/src/scss/_components/_selector/_states/_state-hover.scss
  packages/ui/accordion/src/accordion-context.ts
  packages/ui/accordion/src/accordion-item.tsx
  packages/ui/accordion/src/accordion.tsx
  packages/ui/accordion/src/accordion.types.ts
  packages/ui/accordion/stories/Accordion.stories.tsx
  packages/ui/accordion/stories/tabs/TabCode.mdx
  packages/ui/notification/stories/images/location.svg
  packages/ui/notification/stories/tabs/TabExamples.mdx
  packages/ui/notification/stories/tabs/TabUsage.mdx
  packages/ui/select/src/elements/select-dropdown.tsx
  packages/ui/selector/src/selector.option.tsx
  packages/ui/selector/stories/selector.stories.tsx
  packages/ui/tabs/src/elements/tab-nav.tsx
  packages/ui/tree-view/src/tree-view-context.tsx
  packages/ui/tree-view/src/tree-view-info.tsx
Labels: bug
