Repository wpmudev/sui-react, pull requests merged in 2023-09, with the labels that each got.

#76 ✨ new(navigation): navigation markup changes.
  packages/components/button/src/button-toggle.tsx
  packages/components/button/src/button.tsx
  packages/components/button/src/button.types.ts
  packages/components/button/stories/ReactButton.stories.js
  packages/components/button/stories/tabs/Examples/Icon.mdx
  packages/components/button/stories/tabs/TabCode.mdx
  packages/components/date-picker/src/date-picker-nav.tsx
  packages/components/dropdown/src/dropdown.tsx
  packages/components/navigation/src/navigation-brand.tsx
  packages/components/navigation/src/navigation-user.tsx
  packages/components/navigation/stories/navigatioin.stories.tsx
Labels: enhance

#77 ✨ new(recipient): recipient markup fixes.
  packages/components/recipient/src/recipient-button.tsx
  packages/components/recipient/stories/ReactRecipient.stories.js
Labels: enhance

#78 ✨ new(recipient): recipient status.
  packages/components/recipient/src/recipient.tsx
  packages/components/recipient/stories/ReactRecipient.stories.js
Labels: enhance

#79 ✨ new(footer): footer markup updated.
  packages/components/footer/src/footer.tsx
  packages/components/footer/stories/footer.stories.tsx
Labels: enhance

#80 ✨ new(upsell): upsell markup changes.
  packages/components/upsell/src/helpers.ts
  packages/components/upsell/src/upsell.tsx
  packages/components/upsell/stories/upsell.stories.tsx
Labels: enhance

#84 ✨ new(editor-toolbar): Editor toolbar markup changes.
  packages/components/editor-toolbar/src/editor-toolbar.tsx
  packages/components/editor-toolbar/stories/editor-toolbar.stories.tsx
  packages/components/segmented-control/src/segmented-control-button.tsx
  packages/components/segmented-control/src/segmented-control.types.ts
Labels: enhance

#87 ✨ new(pagination): pagination markup changes.
  packages/components/pagination/src/index.ts
  packages/components/pagination/src/pagination-nav.tsx
  packages/components/pagination/src/pagination-results.tsx
  packages/components/pagination/src/pagination.tsx
  packages/components/pagination/src/pagination.types.ts
  packages/components/pagination/stories/ReactPagination.stories.tsx
Labels: enhance

#86 ✨ new(sidebar): sidebar markup updated.
  packages/components/sidebar/src/index.ts
  packages/components/sidebar/src/sidebar-dropdown.tsx
  packages/components/sidebar/src/sidebar-item.tsx
  packages/components/sidebar/src/sidebar.types.ts
  packages/components/sidebar/stories/sidebar.stories.tsx
Labels: enhance

#88 Toggle component
  packages/components/toggle/stories/ReactToggle.mdx
  packages/components/toggle/stories/images/anatomy.svg
  packages/components/toggle/stories/images/description.svg
  packages/components/toggle/stories/images/label-only.svg
  packages/components/toggle/stories/images/no-label.svg
  packages/components/toggle/stories/images/states.svg
  packages/components/toggle/stories/tabs/TabCode.mdx
  packages/components/toggle/stories/tabs/TabExamples.mdx
  packages/components/toggle/stories/tabs/TabUsage.mdx
Labels: documentation

#85 Checkbox: documentation
  packages/components/checkbox/stories/ReactCheckbox.mdx
  packages/components/checkbox/stories/images/anatomy.svg
  packages/components/checkbox/stories/images/indeterminate.svg
  packages/components/checkbox/stories/images/inline.svg
  packages/components/checkbox/stories/images/size.svg
  packages/components/checkbox/stories/images/stacked.svg
  packages/components/checkbox/stories/images/states.svg
  packages/components/checkbox/stories/tabs/Examples/BasicCheckbox.tsx
  packages/components/checkbox/stories/tabs/TabCode.mdx
  packages/components/checkbox/stories/tabs/TabExamples.mdx
  packages/components/checkbox/stories/tabs/TabUsage.mdx
Labels: documentation

#93 Avatar component
  packages/components/avatar/stories/ReactAvatar.mdx
  packages/components/avatar/stories/images/icon-type.svg
  packages/components/avatar/stories/images/image-type.svg
  packages/components/avatar/stories/images/other-usage.svg
  packages/components/avatar/stories/images/sizes.svg
  packages/components/avatar/stories/images/status.svg
  packages/components/avatar/stories/tabs/Examples/Size.mdx
  packages/components/avatar/stories/tabs/Examples/Status.mdx
  packages/components/avatar/stories/tabs/Examples/Types.mdx
  packages/components/avatar/stories/tabs/TabCode.mdx
  packages/components/avatar/stories/tabs/TabExamples.mdx
  packages/components/avatar/stories/tabs/TabUsage.mdx
Labels: documentation

#92 Spinner Component
  packages/components/spinner/src/spinner.types.ts
  packages/components/spinner/stories/Spinner.mdx
  packages/components/spinner/stories/images/anatomy.svg
  packages/components/spinner/stories/images/size.svg
  packages/components/spinner/stories/images/variations.svg
  packages/components/spinner/stories/spinner.stories.tsx
  packages/components/spinner/stories/tabs/Examples/HookExample.tsx
  packages/components/spinner/stories/tabs/TabCode.mdx
  packages/components/spinner/stories/tabs/TabExamples.mdx
  packages/components/spinner/stories/tabs/TabUsage.mdx
Labels: documentation

#91 Grid Component
  packages/components/grid/stories/ReactGrid.mdx
  packages/components/grid/stories/images/column-lg.svg
  packages/components/grid/stories/images/column-md.svg
  packages/components/grid/stories/images/column-sm.svg
  packages/components/grid/stories/images/column-xl.svg
  packages/components/grid/stories/images/dimensions.svg
  packages/components/grid/stories/images/grid.svg
  packages/components/grid/stories/images/layout.svg
  packages/components/grid/stories/images/spacing-system.svg
  packages/components/grid/stories/tabs/TabCode.mdx
  packages/components/grid/stories/tabs/TabExamples.mdx
  packages/components/grid/stories/tabs/TabUsage.mdx
Labels: documentation

#95 Score component
  packages/components/score/stories/ReactScore.mdx
  packages/components/score/stories/images/anatomy.png
  packages/components/score/stories/images/anatomy.svg
  packages/components/score/stories/images/size.svg
  packages/components/score/stories/images/states.svg
  packages/components/score/stories/tabs/Examples/Size.mdx
  packages/components/score/stories/tabs/Examples/States.mdx
  packages/components/score/stories/tabs/Examples/Types.mdx
  packages/components/score/stories/tabs/TabCode.mdx
  packages/components/score/stories/tabs/TabExamples.mdx
  packages/components/score/stories/tabs/TabUsage.mdx
Labels: documentation

#90 🐛 fix(fields): improved fields accessibility.
  packages/components/form-field/src/form-field.tsx
  packages/components/form-field/stories/ReactFormField.stories.js
  packages/components/textarea/src/textarea.tsx
  packages/components/textarea/src/textarea.types.ts
  packages/components/textarea/stories/ReactTextarea.stories.js
Labels: enhance

#97 ✨ new(advanced-banner): advanced banner markup fixes.
  packages/components/advanced-banner/src/advanced-banner.tsx
  packages/components/advanced-banner/stories/advanced-banner.stories.js
Labels: enhance

#94 ✨ new(builder): builder field markup changes.
  packages/components/builder/src/builder-button.tsx
  packages/components/builder/src/builder-empty.tsx
  packages/components/builder/src/builder-field.tsx
  packages/components/builder/src/builder-wrapper.tsx
  packages/components/builder/src/builder.tsx
  packages/components/builder/src/builder.types.ts
  packages/components/builder/stories/builder.stories.tsx
Labels: enhance

#81 ✨ new(select): select label and trigger selection not working.
  packages/components/select/src/elements/select-selected.tsx
  packages/components/select/src/variants/select-base.tsx
Labels: bug

#101 ✨ new(search): search field improvement removed select smartsearch.
  packages/components/button/src/button.tsx
  packages/components/input/src/input.tsx
  packages/components/search/src/search.tsx
  packages/components/search/stories/search.stories.js
  packages/components/select/package.json
  packages/components/select/src/elements/select-dropdown.tsx
  packages/components/select/src/elements/select-input.tsx
  packages/components/select/src/elements/select-selected.tsx
  packages/components/select/src/index.ts
  packages/components/select/src/variants/select-base.tsx
  packages/components/select/src/variants/select-smart-search.tsx
  packages/components/select/stories/ReactSelect.stories.js
Labels: enhance

#104 ✨ new(upsell-notice): upsell notice markup changes.
  packages/components/upsell-notice/src/helpers.ts
  packages/components/upsell-notice/src/index.ts
  packages/components/upsell-notice/src/upsell-notice.tsx
  packages/components/upsell-notice/src/upsell-notice.types.ts
  packages/components/upsell-notice/stories/upsell-notice.stories.tsx
Labels: enhance

#106 ✨ new(box): box markup updated.
  packages/components/basic-box/src/basic-box.tsx
  packages/components/basic-box/stories/basic-box.stories.js
  packages/components/setting-block/src/setting-block.tsx
Labels: enhance

#105 Sidebar component
  packages/components/sidebar/src/sidebar-item.tsx
  packages/components/sidebar/src/sidebar.tsx
  packages/components/sidebar/src/sidebar.types.ts
  packages/components/sidebar/stories/Sidebar.mdx
  packages/components/sidebar/stories/images/anatomy.svg
  packages/components/sidebar/stories/images/navigation-item.svg
  packages/components/sidebar/stories/images/responsive.svg
  packages/components/sidebar/stories/images/sidebar-spacing.svg
  packages/components/sidebar/stories/images/sidebar-variations.svg
  packages/components/sidebar/stories/tabs/Examples/GeneralSidebar.tsx
  packages/components/sidebar/stories/tabs/TabCode.mdx
  packages/components/sidebar/stories/tabs/TabExamples.mdx
  packages/components/sidebar/stories/tabs/TabUsage.mdx
Labels: documentation

#103 Empty state
  packages/components/empty-state/src/empty-state.types.ts
  packages/components/empty-state/stories/EmptyState.mdx
  packages/components/empty-state/stories/empty-state.stories.tsx
  packages/components/empty-state/stories/images/anatomy.png
  packages/components/empty-state/stories/images/anatomy.svg
  packages/components/empty-state/stories/images/layout-spacing-two.svg
  packages/components/empty-state/stories/images/layout-spacing.svg
  packages/components/empty-state/stories/images/responsive-large.svg
  packages/components/empty-state/stories/images/responsive-medium.svg
  packages/components/empty-state/stories/images/responsive-small.svg
  packages/components/empty-state/stories/tabs/TabCode.mdx
  packages/components/empty-state/stories/tabs/TabExamples.mdx
  packages/components/empty-state/stories/tabs/TabUsage.mdx
Labels: documentation

#102 Code snippet
  packages/components/code-snippet/stories/ReactCodeSnippet.mdx
  packages/components/code-snippet/stories/images/anatomy.png
  packages/components/code-snippet/stories/images/anatomy.svg
  packages/components/code-snippet/stories/images/copied.svg
  packages/components/code-snippet/stories/images/overview.svg
  packages/components/code-snippet/stories/images/scrollbar.svg
  packages/components/code-snippet/stories/images/spacing.svg
  packages/components/code-snippet/stories/images/variations.svg
  packages/components/code-snippet/stories/tabs/TabCode.mdx
  packages/components/code-snippet/stories/tabs/TabExamples.mdx
  packages/components/code-snippet/stories/tabs/TabUsage.mdx
Labels: documentation

#100 Code editor
  packages/components/code-editor/stories/ReactCodeEditor.mdx
  packages/components/code-editor/stories/ReactCodeEditor.stories.tsx
  packages/components/code-editor/stories/images/anatomy.png
  packages/components/code-editor/stories/images/anatomy.svg
  packages/components/code-editor/stories/images/overview.svg
  packages/components/code-editor/stories/images/spacing.svg
  packages/components/code-editor/stories/images/types.svg
  packages/components/code-editor/stories/tabs/Examples/CopyButton.mdx
  packages/components/code-editor/stories/tabs/Examples/FileName.mdx
  packages/components/code-editor/stories/tabs/Examples/Languages.mdx
  packages/components/code-editor/stories/tabs/Examples/LinesNumbers.mdx
  packages/components/code-editor/stories/tabs/Examples/ReadOnly.mdx
  packages/components/code-editor/stories/tabs/TabCode.mdx
  packages/components/code-editor/stories/tabs/TabExamples.mdx
  packages/components/code-editor/stories/tabs/TabUsage.mdx
Labels: documentation

#99 Alert Banner
  packages/components/alert-banner/src/alert-banner.types.ts
  packages/components/alert-banner/stories/alert-banner.mdx
  packages/components/alert-banner/stories/images/anouncement-display.svg
  packages/components/alert-banner/stories/images/anouncement.svg
  packages/components/alert-banner/stories/images/banner-display.svg
  packages/components/alert-banner/stories/images/inline-anatomy.svg
  packages/components/alert-banner/stories/images/inline-variation-error.svg
  packages/components/alert-banner/stories/images/inline-variation-informative.svg
  packages/components/alert-banner/stories/images/inline-variation-success.svg
  packages/components/alert-banner/stories/images/inline-variation-warning.svg
  packages/components/alert-banner/stories/images/mobile-variations/blue.svg
  packages/components/alert-banner/stories/images/mobile-variations/green.svg
  packages/components/alert-banner/stories/images/mobile-variations/light-blue.svg
  packages/components/alert-banner/stories/images/mobile-variations/red.svg
  packages/components/alert-banner/stories/images/mobile-variations/sky-blue.svg
  packages/components/alert-banner/stories/images/mobile-variations/yellow.svg
  packages/components/alert-banner/stories/images/toast-anatomy.svg
  packages/components/alert-banner/stories/images/toast-variation-error.svg
  packages/components/alert-banner/stories/images/toast-variation-informative.svg
  packages/components/alert-banner/stories/images/toast-variation-success.svg
  packages/components/alert-banner/stories/images/toast-variation-warning.svg
  packages/components/alert-banner/stories/images/variations.svg
  packages/components/alert-banner/stories/tabs/Examples/Style.mdx
  packages/components/alert-banner/stories/tabs/Examples/Variations.mdx
  packages/components/alert-banner/stories/tabs/TabCode.mdx
  packages/components/alert-banner/stories/tabs/TabExamples.mdx
  packages/components/alert-banner/stories/tabs/TabUsage.mdx
Labels: documentation

#98 Tooltip component
  packages/components/tooltip/src/elements/tooltip-icon.tsx
  packages/components/tooltip/src/tooltip.tsx
  packages/components/tooltip/stories/ReactTooltip.mdx
  packages/components/tooltip/stories/ReactTooltip.stories.js
  packages/components/tooltip/stories/images/anatomy.png
  packages/components/tooltip/stories/images/anatomy.svg
  packages/components/tooltip/stories/images/caret-position-horizontal.svg
  packages/components/tooltip/stories/images/caret-position-vertical.svg
  packages/components/tooltip/stories/images/overflow.svg
  packages/components/tooltip/stories/images/position.svg
  packages/components/tooltip/stories/images/spacing.png
  packages/components/tooltip/stories/images/spacing.svg
  packages/components/tooltip/stories/tabs/Examples/Position.mdx
  packages/components/tooltip/stories/tabs/Examples/Types.mdx
  packages/components/tooltip/stories/tabs/Examples/states/Success.mdx
  packages/components/tooltip/stories/tabs/TabCode.mdx
  packages/components/tooltip/stories/tabs/TabExamples.mdx
  packages/components/tooltip/stories/tabs/TabUsage.mdx
Labels: documentation

#107 Summary box component
  packages/components/summary-box/src/index.ts
  packages/components/summary-box/src/summary-box-body.tsx
  packages/components/summary-box/src/summary-box.types.ts
  packages/components/summary-box/stories/SummaryBox.mdx
  packages/components/summary-box/stories/images/anatomy.png
  packages/components/summary-box/stories/images/anatomy.svg
  packages/components/summary-box/stories/images/header.svg
  packages/components/summary-box/stories/images/list-interaction.svg
  packages/components/summary-box/stories/images/location.svg
  packages/components/summary-box/stories/images/spacings.svg
  packages/components/summary-box/stories/images/summary.svg
  packages/components/summary-box/stories/summary-box.stories.tsx
  packages/components/summary-box/stories/tabs/TabCode.mdx
  packages/components/summary-box/stories/tabs/TabExamples.mdx
  packages/components/summary-box/stories/tabs/TabUsage.mdx
Labels: documentation

#110 ✨ new(password): password field accessiblity fixes.
  packages/components/field-password/src/field-password.tsx
  packages/components/field-password/src/field-password.types.ts
  packages/components/field-password/stories/ReactFieldPassword.stories.js
  packages/components/field-password/stories/tabs/Examples/ButtonType.mdx
  packages/components/field-password/stories/tabs/Examples/Size.mdx
  packages/components/field-password/stories/tabs/Examples/States.mdx
  packages/components/field-password/stories/tabs/TabCode.mdx
  packages/components/field-password/stories/tabs/TabExamples.mdx
  packages/components/form-field/src/elements/error-message.tsx
  packages/components/form-field/src/elements/helper.tsx
  packages/components/form-field/src/elements/label.tsx
  packages/components/form-field/src/form-field.tsx
  packages/components/form-field/stories/ReactFormField.stories.js
Labels: enhance

#108 ✨ new(radio): added radio group.
  packages/components/radio/src/index.tsx
  packages/components/radio/src/radio-context.ts
  packages/components/radio/src/radio-group.tsx
  packages/components/radio/src/radio.tsx
  packages/components/radio/src/radio.types.ts
  packages/components/radio/stories/ReactRadio.stories.js
  packages/components/tag/src/tag.tsx
  packages/components/tag/src/tag.types.ts
  packages/components/tag/stories/ReactTag.stories.js
Labels: enhance

#120 ✨ new(datepicker): datepicker accessibility improvements.
  packages/components/date-picker/src/date-picker-input.tsx
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/date-picker.types.ts
  packages/components/date-picker/stories/DatePicker.stories.tsx
Labels: enhance

#115 ✨ new(colorpicker): color picker markup changes.
  packages/components/color-picker/src/color-picker.tsx
  packages/components/color-picker/src/color-picker.types.ts
  packages/components/color-picker/stories/ReactColorPicker.stories.tsx
  packages/components/input/stories/ReactInput.stories.js
Labels: enhance

#111 ✨ new(progress): progress bar markup updated.
  packages/components/progress-bar/src/progress-bar.tsx
  packages/components/progress-bar/src/progress-bar.types.ts
  packages/components/progress-bar/stories/ReactProgressBar.stories.js
Labels: enhance

#121 ✨ new(form field): removed unused Text field component.
  packages/components/field-text/.gitignore
  packages/components/field-text/CHANGELOG.md
  packages/components/field-text/LICENSE
  packages/components/field-text/README.md
  packages/components/field-text/__tests__/field-text.test.js
  packages/components/field-text/package.json
  packages/components/field-text/src/index.ts
  packages/components/field-text/src/text-field.tsx
  packages/components/field-text/src/text-field.types.ts
  packages/components/field-text/stories/ReactFieldText.mdx
  packages/components/field-text/stories/ReactFieldText.stories.js
  packages/components/field-text/stories/images/anatomy.svg
  packages/components/field-text/stories/images/icons.svg
  packages/components/field-text/stories/images/size.svg
  packages/components/field-text/stories/images/states.svg
  packages/components/field-text/stories/tabs/Examples/Icon.mdx
  packages/components/field-text/stories/tabs/Examples/Size.mdx
  packages/components/field-text/stories/tabs/Examples/States.mdx
  packages/components/field-text/stories/tabs/TabCode.mdx
  packages/components/field-text/stories/tabs/TabExamples.mdx
  packages/components/field-text/stories/tabs/TabUsage.mdx
  packages/components/form-field/stories/ReactFormField.mdx
  packages/components/form-field/stories/ReactFormField.stories.js
Labels: enhance

#119 Pagination Component
  packages/components/pagination/src/pagination.tsx
  packages/components/pagination/src/pagination.types.ts
  packages/components/pagination/stories/ReactPagination.mdx
  packages/components/pagination/stories/ReactPagination.stories.tsx
  packages/components/pagination/stories/images/anatomy.svg
  packages/components/pagination/stories/images/spacing.svg
  packages/components/pagination/stories/images/states.svg
  packages/components/pagination/stories/images/variations.svg
  packages/components/pagination/stories/tabs/Examples/Examples.jsx
  packages/components/pagination/stories/tabs/TabCode.mdx
  packages/components/pagination/stories/tabs/TabExamples.mdx
  packages/components/pagination/stories/tabs/TabUsage.mdx
Labels: documentation

#114 Advanced Banner
  packages/components/advanced-banner/src/advanced-banner.tsx
  packages/components/advanced-banner/src/advanced-banner.types.ts
  packages/components/advanced-banner/stories/advanced-banner.mdx
  packages/components/advanced-banner/stories/advanced-banner.stories.js
  packages/components/advanced-banner/stories/images/anatomy.svg
  packages/components/advanced-banner/stories/images/display-location.svg
  packages/components/advanced-banner/stories/images/high-contrast-mode.svg
  packages/components/advanced-banner/stories/images/spacing.svg
  packages/components/advanced-banner/stories/images/tag.svg
  packages/components/advanced-banner/stories/images/variations.svg
  packages/components/advanced-banner/stories/tabs/Examples/States.mdx
  packages/components/advanced-banner/stories/tabs/Examples/Variations.mdx
  packages/components/advanced-banner/stories/tabs/TabCode.mdx
  packages/components/advanced-banner/stories/tabs/TabExamples.mdx
  packages/components/advanced-banner/stories/tabs/TabUsage.mdx
Labels: documentation

#118 Editor Toolbar
  packages/components/editor-toolbar/src/editor-toolbar.tsx
  packages/components/editor-toolbar/src/editor-toolbar.types.ts
  packages/components/editor-toolbar/stories/editor-toolbar.mdx
  packages/components/editor-toolbar/stories/images/anatomy.svg
  packages/components/editor-toolbar/stories/images/high-contrast.svg
  packages/components/editor-toolbar/stories/images/overview.svg
  packages/components/editor-toolbar/stories/images/responsive.svg
  packages/components/editor-toolbar/stories/images/saving-status.svg
  packages/components/editor-toolbar/stories/images/spacing.svg
  packages/components/editor-toolbar/stories/images/types.svg
  packages/components/editor-toolbar/stories/tabs/TabCode.mdx
  packages/components/editor-toolbar/stories/tabs/TabExamples.mdx
  packages/components/editor-toolbar/stories/tabs/TabUsage.mdx
Labels: documentation

#116 Builder Component
  packages/components/builder/stories/builder.mdx
  packages/components/builder/stories/builder.stories.tsx
  packages/components/builder/stories/images/block/accordion.svg
  packages/components/builder/stories/images/block/anatomy.svg
  packages/components/builder/stories/images/block/spacings.svg
  packages/components/builder/stories/images/block/states.svg
  packages/components/builder/stories/images/block/type.svg
  packages/components/builder/stories/images/block/variations.svg
  packages/components/builder/stories/images/builder/anatomy.svg
  packages/components/builder/stories/images/builder/button-states.svg
  packages/components/builder/stories/images/builder/columns.svg
  packages/components/builder/stories/images/builder/dragging-block.svg
  packages/components/builder/stories/images/builder/drop-zone-position.svg
  packages/components/builder/stories/images/builder/empty-state.svg
  packages/components/builder/stories/images/builder/mobile.svg
  packages/components/builder/stories/images/builder/spacing.svg
  packages/components/builder/stories/tabs/Examples/BuilderStates.mdx
  packages/components/builder/stories/tabs/Examples/FieldsStates.mdx
  packages/components/builder/stories/tabs/TabBlocks.mdx
  packages/components/builder/stories/tabs/TabCode.mdx
  packages/components/builder/stories/tabs/TabExamples.mdx
  packages/components/builder/stories/tabs/TabUsage.mdx
Labels: documentation

#123 🐛 fix(fields): fields error state fixes.
  packages/components/date-picker/stories/DatePicker.stories.tsx
  packages/components/field-password/stories/ReactFieldPassword.mdx
  packages/components/field-password/stories/ReactFieldPassword.stories.js
  packages/components/field-password/stories/tabs/Examples/ButtonType.mdx
  packages/components/field-password/stories/tabs/Examples/Size.mdx
  packages/components/field-password/stories/tabs/Examples/States.mdx
  packages/components/field-password/stories/tabs/TabExamples.mdx
  packages/components/form-field/src/form-field.tsx
  packages/components/form-field/stories/ReactFormField.stories.js
  packages/components/input/stories/ReactInput.stories.js
Labels: bug
